# serverless.yml

service: apollo-lambda
provider:
  name: aws
  runtime: nodejs8.10
  profile: angular-spotify-graphql-serverless
  stage: dev
  region: us-east-1
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: graphql.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true